# Generated by Django 4.2.14 on 2025-08-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_bill_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitemvariant',
            name='preparation_time',
            field=models.PositiveIntegerField(default=15, help_text='Preparation time in minutes'),
        ),
    ]
