# Generated by Django 4.2.14 on 2025-08-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menuitemvariant_preparation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('OFFLINE', 'Offline'), ('ONLINE', 'Online')], max_length=20, null=True),
        ),
    ]
