# menu/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (
    PublicMenuListView, OrderCreateView, ChefOrderItemUpdateView, 
    CaptainOrderCreateView, CaptainReorderView, CashierBillListView, 
    CashierMarkAsPaidView, AdminAnalyticsView,
    MenuItemManageViewSet, CategoryManageViewSet, FoodTypeViewSet, 
    CuisineViewSet , RestaurantOrderViewSet , RestaurantAnalyticsView,
    FrontendOrderCreateView , KitchenOrderListView, AdminOrderReportView
)
from .views import AddItemsToOrderView 
from .views import OrderDetailView

# Create a router for all the management ViewSets
router = DefaultRouter()
router.register(r'menu-items', MenuItemManageViewSet, basename='menuitem-manage')
router.register(r'categories', CategoryManageViewSet, basename='category-manage')
router.register(r'food-types', FoodTypeViewSet, basename='foodtype-manage')
router.register(r'cuisines', CuisineViewSet, basename='cuisine-manage')
router.register(r'orders', RestaurantOrderViewSet, basename='restaurant-order')

urlpatterns = [
    # --- Public Customer URLs ---
    path('restaurants/<slug:restaurant_slug>/menu/', PublicMenuListView.as_view(), name='public-menu-list'),
    path('restaurants/<slug:restaurant_slug>/orders/', FrontendOrderCreateView.as_view(), name='frontend-order-create'),
    # --- Internal Staff URLs ---
    path('order-items/<int:item_id>/update-status/', ChefOrderItemUpdateView.as_view(), name='update-order-item-status'),
    path('captain/orders/create/', CaptainOrderCreateView.as_view(), name='captain-order-create'),
    path('captain/bills/<int:bill_id>/reorder/', CaptainReorderView.as_view(), name='captain-reorder'),
    path('cashier/pending-bills/', CashierBillListView.as_view(), name='cashier-bill-list'),
    path('cashier/bills/<int:bill_id>/pay/', CashierMarkAsPaidView.as_view(), name='cashier-mark-as-paid'),
    # --- Admin Analytics URL ---
    path('admin/analytics/', AdminAnalyticsView.as_view(), name='admin-analytics'),
    # --- Restaurant Admin Management URLs ---
    # This single line includes all the URLs generated by the router above
    path('restaurant/', include(router.urls)),
    # path for the restaurant-specific analytics
    path('restaurant/analytics/', RestaurantAnalyticsView.as_view(), name='restaurant-analytics'),
    # This line for the router should be last in this section
    path('restaurant/', include(router.urls)),
    # path for the Kitchen's initial order list
    path('kitchen/orders/', KitchenOrderListView.as_view(), name='kitchen-order-list'),
    # path for the admin's historical order report
    path('restaurant/reports/orders/', AdminOrderReportView.as_view(), name='admin-order-report'),

    path('orders/<int:bill_id>/add_items/', AddItemsToOrderView.as_view(), name='add-items-to-order'),

    path('orders/<int:order_id>/', OrderDetailView.as_view(), name='order-detail'),
]