# Generated by Django 5.2.5 on 2025-08-28 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
        ('users', '0002_staffuser_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('CAPTAIN', 'Captain'), ('CHEF', 'Chef'), ('CASHIER', 'Cashier')], max_length=50)),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=128)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_credentials', to='restaurants.restaurant')),
            ],
            options={
                'unique_together': {('restaurant', 'role')},
            },
        ),
    ]
